load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_oci//oci:defs.bzl", "oci_image")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//push_oci:push_oci.bzl", "push_oci")

tar(
    name = "image_tar",
    srcs = [":container_content.txt"],
)

oci_image(
    name = "image",
    architecture = "amd64",
    os = "linux",
    tars = [":image_tar"],
    visibility = ["//visibility:public"],
)

push_oci(
    name = "image_push",
    image = ":image",
    # tag = "test_tag",
    repository = "us-central1-docker.pkg.dev/fasterci/internal/push_oci/tests/image_push",
)

write_file(
    name = "tags_file",
    out = "tags.txt",
    content = ["testtag"],
)

push_oci(
    name = "oci_integration_push",
    image = ":image",
    remote_tags = ":tags_file",
    repository = "localhost:1338/repo/oci_img",
)

sh_test(
    name = "integration_test",
    size = "small",
    srcs = ["integration_test.sh"],
    tags = ["exclusive"],
    args = [
        "$(location :oci_integration_push)",
    ],
    data = [
        ":oci_integration_push",
        "@com_github_google_go_containerregistry//cmd/crane",
        "@com_github_google_go_containerregistry//cmd/registry",
    ],
    env = {
        "CRANE_BIN": "$(location @com_github_google_go_containerregistry//cmd/crane)",
        "REGISTRY_BIN": "$(location @com_github_google_go_containerregistry//cmd/registry)",
    },
)
