apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ci
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: docker.io/skylib/kustomize/tests/image@sha256:d3ae39f0863977b626c3e61b49f8d6ebc08c119fc7ce59ca09e95e0128c04423
        name: myapp
