load("@rules_img//img:layer.bzl", "image_layer")
load("@rules_img//img:image.bzl", "image_manifest")
load("//push_oci:push_oci.bzl", "push_oci")

image_layer(
    name = "layer",
    srcs = {
        "/container_content.txt": ":container_content.txt",
    },
)

image_manifest(
    name = "image",
    layers = [":layer"],
    visibility = ["//visibility:public"],
)

push_oci(
    name = "image_push",
    image = ":image",
    repository = "us-central1-docker.pkg.dev/fasterci/internal/push_img/tests/image_push",
)

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

write_file(
    name = "tags_file",
    out = "tags.txt",
    content = ["testtag"],
)

push_oci(
    name = "img_integration_push",
    image = ":image",
    remote_tags = ":tags_file",
    repository = "localhost:1338/repo/img",
)

sh_test(
    name = "integration_test",
    size = "small",
    srcs = ["integration_test.sh"],
    args = [
        "$(location :img_integration_push)",
    ],
    data = [
        ":img_integration_push",
        "@com_github_google_go_containerregistry//cmd/crane",
        "@com_github_google_go_containerregistry//cmd/registry",
    ],
    env = {
        "CRANE_BIN": "$(location @com_github_google_go_containerregistry//cmd/crane)",
        "REGISTRY_BIN": "$(location @com_github_google_go_containerregistry//cmd/registry)",
    },
)
